feign:
  httpclient:
    enabled: false
    disable-ssl-validation: true
  okhttp:
    enabled: true
  client:
    config:
      defailt:
        connectionTimeout: {{APP_HTTP_CONNECTION_TIMEOUT}}
        readTimeout: {{APP_HTTP_CONNECTION_TIMEOUT}}
        loggerLevel: {{APP_HTTP_LOG_LEVEL}}
      kinesis:
        connectionTimeout: {{APP_HTTP_DEFERRED_CONNECTION_TIMEOUT}}
        readTimeout: {{APP_HTTP_DEFERRED_CONNECTION_TIMEOUT}}
---
context:
  kinesis-data-pipe:  test/

---
client:
  gateway:
    url: {{APP_HTTP_CLIENT_GATEWAY_URL}}
  retry:
    period: {{APP_HTTP_CLIENT_RETRY_PERIOD}}
    max-period: {{APP_HTTP_CLIENT_RETRY_MAX_PERIOD}}
    max-attempts: {{APP_HTTP_CLIENT_RETRY_MAX_ATTEMPTS}}
  config:
    kinesis:
      id: kinesis
      url: ${client.gateway.url}
      path: ${context.kinesis-data-pipe}